l1classifiers: l1de l1es l1fr l1it l1nl

l1de:
	python3 pickle_l1_classifiers.py de
l1es:
	python3 pickle_l1_classifiers.py es
l1fr:
	python3 pickle_l1_classifiers.py fr
l1it:
	python3 pickle_l1_classifiers.py it
l1nl:
	python3 pickle_l1_classifiers.py nl

l1experiments: l1_exp_de l1_exp_es l1_exp_fr l1_exp_it l1_exp_nl

l1_exp_de:
	./run_one_l1_language.sh de
l1_exp_es:
	./run_one_l1_language.sh es
l1_exp_fr:
	./run_one_l1_language.sh fr
l1_exp_it:
	./run_one_l1_language.sh it
l1_exp_nl:
	./run_one_l1_language.sh nl
